### ISSUE TITLE
A bit unsure and discussion around the gems use of dictionary

### ISSUE THREAD

**Issue by travisdmathis** [bdmac/strong_password#11]
Is there a reason you're using dictionary checks?  It really doesn't make much sense if you're checking entropy.  There should be no words that are "bad" as a password of "my brown dog jumps high" is a better password and has more entropy than say, "mybr0wnd0gjump5h1gh".  In this case spoken words are better and should not be a negative as its easier to remember long passwords.  I came across your project as I was annoyed by the way password strength is getting kind of ridiculous and not really all that much stronger, just more terrible requirements and wanted to solve this problem once and for all.

All that should truly matter is the amount of entropy one has to prevent brute force attacks, no?

"my brown dog jumps high"
Length: 23
Strength: Strong - This password is typically good enough to safely guard sensitive information like financial records.
Entropy: 89.5 bits
Charset Size: 27 characters

"mybr0wnd0gjump5h1gh"
Length: 19
Strength: Strong - This password is typically good enough to safely guard sensitive information like financial records.
Entropy: 82.3 bits
Charset Size: 36 characters

Just some discussion, may fork and jump in on the project.

**Comment by bdmac** [comment]
That is basically why this project was started so I think we agree there. This is not a true dictionary check. The dictionary here consists of only the most common passwords as determined by hacked password lists. Many of the words aren't actually "words". The goal is to penalize entropy on shorter phrases containing words from that list. Without this there are some relatively common passwords that have high enough entropy depending on what your minimum is. That said the dictionary check can be disabled.

**Comment by travisdmathis** [comment]
thanks for the clarification.. think i'll jump in.
