### ISSUE TITLE
Optimise memory usage

### ISSUE THREAD

**Issue by stereobooster** [bdmac/strong_password#12]
This [file](https://github.com/bdmac/strong_password/blob/master/lib/strong_password/dictionary_adjuster.rb) loads every common password in memory as ruby string e.g. object. We can try to do the same trick as in [mini_mime](https://github.com/discourse/mini_mime/blob/master/lib/mini_mime.rb#L80)

```
bundle exec derailed bundle:objects | head -n 100
Measuring objects created by gems in groups [:default, "production"]

allocated memory by gem
-----------------------------------
   3137392  strong_password-0.0.4
```

**Comment by bdmac** [comment]
Yah it definitely loads a ton of data. PRs 💯 welcome!

**Comment by stereobooster** [comment]
I have primitive solution COMMON_PASSWORDS = "long strings"

And split string just before usage. This will not decrease real memory, but will decrease object allocation, when we do not use functionally, just loading gem

**Comment by stereobooster** [comment]
Maybe [compressed trie data structure](https://github.com/gonzedge/rambling-trie) will help

**Comment by stereobooster** [comment]
I have no time to do this, so will close. Thanks
