### ISSUE TITLE
Bump version number?

### ISSUE THREAD

**Issue by fny** [bdmac/strong_password#15]
Is there any reason we're stuck at pre 0.1.0 or 1.0.0? Given there hasn't been much development here, it might be worth considering. My biggest hesitation for using this in production is that the version number doesn't suggest much stability. ;)

**Comment by bdmac** [comment]
Apologies. No there's no particular reason other than the lack of development but that's mostly because it just worked for our use-case. Hopefully the version number just suggests lack of change which I guess is a form of stability at the end of the day...
