### ISSUE TITLE
Feature Request: Check for repetitive or sequential characters

### ISSUE THREAD

**Issue by lancecarlson** [bdmac/strong_password#16]
As per the NIST requirements, they include a check for repetitive or sequential characters e.g. 'aaaaaa', '1234abcd'). Would this be something you would consider adding? If I have time I could work on it. :)

**Comment by bdmac** [comment]
The code already does this.

**Comment by lancecarlson** [comment]
Oh BTW, I added your gem to this wiki page because I found it so useful!

https://github.com/plataformatec/devise/wiki/How-To:-Set-up-simple-password-complexity-requirements

**Comment by bdmac** [comment]
It may not do that exactly I guess. https://github.com/bdmac/strong_password/blob/master/lib/strong_password/entropy_calculator.rb#L31 does something along those lines but I think for just repeats anywhere in the string. I've actually stopped using this because it's hard to let people know what your password rules are using a lib like this. If you want to try to add something as an option go for it! :)

**Comment by lancecarlson** [comment]
@bdmac What do you use instead? I actually think it's easy if you just tell the user they're using a commonly used password as the error message.

**Comment by bdmac** [comment]
Yes, but building something like a password strength indicator is harder on the front-end and you can't put a help/tooltip that says 1 upper, 1 lower, 1 number, 1 symbol or whatever. I dislike those too but they're at least slightly more user friendly than just telling someone their password is too weak but not telling them why at all. This does so many checks that in many cases it prevents users from using their normal passwords that most sites would find "secure" (like p@s$w0rd). This is a good thing in theory but really annoying to people in practice. Unless you're guarding financial data or something it tends to be overkill and that's not what I was using this for.

**Comment by lancecarlson** [comment]
I gotcha. I guess the most useful thing I found about this library was your dictionary validater, which is the only thing I use, haha!

**Comment by lancecarlson** [comment]
I'm going to close this and reopen if I have time to work on it
