### ISSUE TITLE
Long password denial of service vulnerability

### ISSUE THREAD

**Issue by cianmce** [bdmac/strong_password#17]
## Issue
A user can enter a long password and take a server offline for a large amount of time
As seen below a single request with a long password of 10,00,000 characters can result in a server being frozen for ~ 5 minutes.
This means that with just a single computer an attacker can easily make a few requests to take a number of machines offline and achieve an effective DOS attack

## Proposed solution
OWASP recommends using a limit of 1,000
> A limit of **1000 characters** is sufficient to let the user choose a very big password without impacting the system.
> https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet#Input_password_size

In order to make this backwards compatible and to not affect any existing long passwords, truncating of the users input passwords could be done. In all cases, a password of 1,000 should be just as "Strong" as one of 10,000

## Not affected
Rails applications using bcrypt are not affected as they have a limit of 72 enforced:
https://github.com/rails/rails/blob/040eb98c2be6bfb2c50b4ad85e7031f9aa97f15e/activemodel/lib/active_model/secure_password.rb#L7-L10
**UNLESS** they are manually checking password strength before attempting to persist it to the DB

## Benchmarks

Benchmarks for password lengths with this gem can be seen here: [cianmce/benchmark_password_gems](https://github.com/cianmce/benchmark_password_gems)

A Google sheet of the results can be seen [here](https://docs.google.com/spreadsheets/d/1zhLz7iRuo4nt-HD9B9eN7nh_ejaoAlO9K8ZO6tngZwM/edit#gid=1175290289)

[![bdmac-strong_password](https://user-images.githubusercontent.com/4098222/46262107-af7bf180-c4f4-11e8-87c6-a33f72a5b005.png)](https://docs.google.com/spreadsheets/d/1zhLz7iRuo4nt-HD9B9eN7nh_ejaoAlO9K8ZO6tngZwM/edit#gid=1175290289)

##  Live Demo
Site: [password-dos.herokuapp.com](https://password-dos.herokuapp.com/)

Source: [cianmce/profile_password_checkers](https://github.com/cianmce/profile_password_checkers
)

**Comment by dgsan** [comment]
Should this be closed now?
