### ISSUE TITLE
Extra Dictionary Words need to be lowercase

### ISSUE THREAD

**Issue by chbach** [bdmac/strong_password#23]
I recently discovered that the additional dictionary words don’t have any effect if they’re not provided in lowercase format. This should at least be mentioned in the documentation. 

Example:

```ruby
pw = 'FancyPants12'
ps = ::StrongPassword::StrengthChecker.new(pw)

ps.calculate_entropy(use_dictionary: true)
=> 16
ps.calculate_entropy(use_dictionary: true, extra_dictionary_words: [pw])
=> 16
ps.calculate_entropy(use_dictionary: true, extra_dictionary_words: [pw.downcase])
=> 2
```

**Comment by bdmac** [comment]
I tried writing a failing spec for this but it passed when provided with a "Administrator" instead of "administrator" for the extra dictionary word.
