### ISSUE TITLE
Document breaking change

### ISSUE THREAD

**Issue by philayres** [bdmac/strong_password#26]
On the recent upgrade to 0.0.8 the requirements for initialisation of **StrengthChecker** changed, from:

    StrongPassword::StrengthChecker.new password

to

    StrongPassword::StrengthChecker.new config_hash

And subsequently calls to methods such as **#calculate_entropy** take the password to be checked as opposed to the configuration.

This is a note for others to find that might be taken by surprise by this change.

This is also a request to document breaking changes like this in the README in future. I understand this is 0.0.x change, but as I'm sure people (like me) are using this library in production it may be worth considering bumping the versioning up to a higher level, and documenting breaking changes on a minor version update.

I'd be happy to help with PRs in the future if this would be acceptable.

**Comment by bdmac** [comment]
Thanks. The minimal documentation on standalone usage did update to reflect this but it being < a 1.0 version it did not seem as important to call this out specifically. Feel free to submit a README update!

**Comment by philayres** [comment]
Do you have a plan to bump the versions to a minor or major release at any point?

**Comment by bdmac** [comment]
No current plans, no.
