### ISSUE TITLE
Release 0.0.9 not tagged

### ISSUE THREAD

**Issue by GeoffKarnov** [bdmac/strong_password#38]
[Version 0.0.9 as released on Rubygems](https://rubygems.org/gems/strong_password/versions/0.0.9)  does not have a [tag here on Github](https://github.com/bdmac/strong_password/tags)

I believe it should be: 265eacbe75c9b5e9a2b66e0eace8597678ed5c9d

**Comment by xmunoz** [comment]
+1, please add the tag so devs know what code their depending on.

**Comment by bdmac** [comment]
Tag added, thanks!
